### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by andremleblanc** [andremleblanc/frc#5]
### Description
Messages MVC that allows sending a message immediately or in the future.

### Sub-Tasks
- [x] Use Devise for authentication
- [x] Create MVC
- [x] Use Administrate for administration
- [x] Use Sidekiq for Jobs
- [x] Use Twilio for SMS service
- [x] Use Test Service to Diagnose Sidekiq Issue (Use Test API)
- [x] Write Specs
